import ClientAreaLayout from "@/components/ClientAreaLayout";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Link } from "wouter";
import { CircleHelp, LifeBuoy, ShieldAlert } from "lucide-react";

const topics = [["Account access", "Use the account provider recovery path if you cannot sign in. If access remains unavailable, contact Digital Junction with the email address linked to your account."], ["Service-project and delivery updates", "Open your service project in Client Side to see milestones and shared deliverables. Contact the team if you need clarification or a delivery update."], ["Digital product requests", "Product requests are handled directly by Digital Junction. Confirmed fulfilment details and downloads will appear in your purchase library."], ["Billing questions", "In-app billing is not configured yet. Contact Digital Junction for invoice, payment, or fulfilment questions."]];
const sampleSupportPreview = [{ subject: "Sample service update question", status: "Preview only" }, { subject: "Sample product-access question", status: "Preview only" }];

export default function ClientSupport() { return <ClientAreaLayout><div className="mx-auto max-w-5xl space-y-6 py-2"><header><p className="eyebrow">Customer support</p><h1 className="display mt-2 text-4xl text-[#1A312C]">Support centre</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#1A312C]/64">Guidance for your Digital Junction customer account, service projects, product orders, billing, and delivery questions.</p></header><section className="grid gap-4 sm:grid-cols-3"><article className="rounded-xl border border-[#1A312C]/10 bg-white/70 p-5"><CircleHelp className="size-5 text-[#428475]" /><p className="mt-4 text-sm font-bold text-[#1A312C]">Account guidance</p></article><article className="rounded-xl border border-[#1A312C]/10 bg-white/70 p-5"><LifeBuoy className="size-5 text-[#428475]" /><p className="mt-4 text-sm font-bold text-[#1A312C]">Service support</p></article><article className="rounded-xl border border-[#1A312C]/10 bg-white/70 p-5"><ShieldAlert className="size-5 text-[#428475]" /><p className="mt-4 text-sm font-bold text-[#1A312C]">Access and security</p></article></section><section className="rounded-[1.35rem] border border-[#1A312C]/10 bg-white/70 p-6 sm:p-8"><h2 className="display text-3xl text-[#1A312C]">Sample support history</h2><div className="mt-4 rounded-xl border border-[#428475]/20 bg-[#89D7B7]/18 px-4 py-3 text-xs leading-5 text-[#1A312C]/72"><strong className="text-[#1A312C]">Sample preview:</strong> these are not submitted tickets, messages, or support records.</div><div className="mt-5 grid gap-3 md:grid-cols-2">{sampleSupportPreview.map(ticket => <article key={ticket.subject} className="rounded-xl bg-[#FFF4E1]/70 p-4"><p className="font-mono text-[0.58rem] uppercase tracking-[0.1em] text-[#428475]">Sample support record</p><p className="mt-2 text-sm font-bold text-[#1A312C]">{ticket.subject}</p><span className="mt-3 inline-flex rounded-full bg-[#89D7B7]/35 px-2.5 py-1 font-mono text-[0.56rem] uppercase text-[#1A312C]/70">{ticket.status}</span></article>)}</div></section><section className="rounded-[1.35rem] border border-[#1A312C]/10 bg-white/70 p-6 sm:p-8"><h2 className="display text-3xl text-[#1A312C]">Helpful answers</h2><Accordion type="single" collapsible className="mt-5">{topics.map(([title, body]) => <AccordionItem key={title} value={title}><AccordionTrigger className="text-left text-sm font-bold text-[#1A312C]">{title}</AccordionTrigger><AccordionContent className="text-sm leading-6 text-[#1A312C]/64">{body}</AccordionContent></AccordionItem>)}</Accordion></section><section className="rounded-[1.35rem] bg-[#428475] p-7 text-[#FFF4E1]"><h2 className="display text-3xl">Need more help?</h2><p className="mt-3 max-w-xl text-sm leading-6 text-[#FFF4E1]/75">Send a concise description of what you need, including the relevant project or product name when possible.</p><Link href="/contact" className="button-secondary buttonlike mt-6">Contact Digital Junction</Link></section></div></ClientAreaLayout>; }
