import { ArrowRight, Blocks, BriefcaseBusiness, Code2, FileText, Globe2, LayoutDashboard, Loader2, Palette, Smartphone, Sparkles, Store, Wrench } from "lucide-react";
import { Link } from "wouter";
import PublicLayout from "@/components/PublicLayout";
import { getPublicSectionDefault } from "@/data/publicContentDefaults";
import { usePublicSection } from "@/hooks/usePublicSection";
import { trpc } from "@/lib/trpc";

const solutionGroups = [
  { title: "Development", description: "Websites, web applications, and mobile experiences built for real goals.", Icon: Code2 },
  { title: "Business Systems", description: "POS, inventory, management systems, and custom software for daily operations.", Icon: LayoutDashboard },
  { title: "Design & Branding", description: "UI/UX, logos, visual identity, and creative assets that make a business recognisable.", Icon: Palette },
  { title: "Digital Products", description: "Templates, UI kits, business resources, and productivity tools made by Digital Junction.", Icon: Store },
];

const services = [
  { title: "Web Development", description: "Professional, responsive, and SEO-friendly websites.", Icon: Globe2 },
  { title: "UI/UX Design", description: "Modern, intuitive, user-centred digital interfaces.", Icon: Palette },
  { title: "Full-Stack Development", description: "Frontend, backend, database, and API solutions.", Icon: Code2 },
  { title: "Mobile App Development", description: "Cross-platform applications for modern businesses.", Icon: Smartphone },
  { title: "POS & Inventory Systems", description: "Sales, inventory, reporting, and operations tools.", Icon: LayoutDashboard },
  { title: "Logo & Branding", description: "Practical visual identities designed for businesses.", Icon: Sparkles },
  { title: "Canva Template Design", description: "Editable templates for businesses, creators, and professionals.", Icon: FileText },
  { title: "Short-form Video Editing", description: "Engaging content for modern social platforms.", Icon: Blocks },
  { title: "Technical Support", description: "Practical support for software, systems, and basic IT needs.", Icon: Wrench },
];

const advantages = [
  ["Modern Design", "Professional, responsive, and user-focused digital experiences."],
  ["Custom Solutions", "Solutions shaped around the actual needs of each project."],
  ["Scalable Development", "Clean, maintainable work designed to grow with the business."],
  ["Affordable & Practical", "Professional digital solutions without unnecessary complexity."],
  ["Reliable Support", "Continued assistance beyond the initial delivery."],
  ["Innovation First", "Continuous learning and adoption of better technologies."],
];

const process = [
  ["01", "Discover", "Understand the idea, goals, requirements, and challenges."],
  ["02", "Plan", "Define the solution, scope, features, and project direction."],
  ["03", "Design & Build", "Create the experience and develop the solution."],
  ["04", "Deliver", "Launch, hand over, and provide continued support when needed."],
];

function money(value: string | number) {
  return new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP", maximumFractionDigits: 2 }).format(Number(value));
}

function HeroVisual({ imageUrl }: { imageUrl?: string }) {
  if (imageUrl) return <img src={imageUrl} alt="Digital Junction feature" className="aspect-[1.04] w-full rounded-[1.65rem] object-cover shadow-[0_22px_70px_rgba(0,0,0,.28)]" />;
  return (
    <div className="art-card relative rounded-[1.65rem] p-4 pb-14 sm:p-5 sm:pb-16">
      <div className="flex items-center justify-between border-b border-[#FFF4E1]/15 pb-4">
        <span className="font-mono text-[0.62rem] uppercase tracking-[0.14em] text-[#89D7B7]">Digital operations</span>
        <span className="flex gap-1.5"><i className="size-2 rounded-full bg-[#89D7B7]" /><i className="size-2 rounded-full bg-[#FFF4E1]/35" /><i className="size-2 rounded-full bg-[#FFF4E1]/35" /></span>
      </div>
      <div className="mt-5 grid gap-4 sm:grid-cols-[1.06fr_.94fr]">
        <div className="rounded-2xl bg-[#FFF4E1] p-5 text-[#1A312C]">
          <p className="font-mono text-[0.63rem] uppercase tracking-[0.12em] text-[#428475]">Your next move</p>
          <h2 className="display mt-4 text-3xl leading-tight">A clear path from idea to launch.</h2>
          <div className="mt-7 grid grid-cols-2 gap-2"><div className="rounded-xl bg-[#89D7B7]/35 p-3"><p className="font-mono text-[0.6rem] uppercase text-[#1A312C]/55">Direction</p><p className="mt-1 text-sm font-bold">Aligned</p></div><div className="rounded-xl bg-[#1A312C] p-3 text-[#FFF4E1]"><p className="font-mono text-[0.6rem] uppercase text-[#89D7B7]">Build</p><p className="mt-1 text-sm font-bold">In motion</p></div></div>
        </div>
        <div className="grid gap-4"><div className="rounded-2xl border border-[#89D7B7]/35 bg-[#1A312C]/70 p-4"><p className="font-mono text-[0.6rem] uppercase tracking-[0.1em] text-[#89D7B7]">Progress</p><div className="mt-4 flex h-16 items-end gap-2">{[28, 52, 37, 69, 57, 82].map((value, index) => <span key={value} className="flex-1 rounded-t-sm bg-[#89D7B7]" style={{ height: `${value}%`, opacity: 0.45 + index * 0.08 }} />)}</div></div><div className="rounded-2xl bg-[#428475] p-4"><p className="font-mono text-[0.6rem] uppercase tracking-[0.1em] text-[#FFF4E1]/65">Next milestone</p><p className="mt-3 text-sm font-semibold leading-5 text-[#FFF4E1]">A practical digital solution, ready to use.</p><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-[#FFF4E1]/25"><div className="h-full w-[68%] rounded-full bg-[#89D7B7]" /></div></div></div>
      </div>
      <div className="absolute bottom-4 left-4 flex items-center gap-3 rounded-2xl border border-[#89D7B7]/30 bg-[#1A312C] px-4 py-3 shadow-xl sm:bottom-5 sm:left-5"><span className="grid size-8 place-items-center rounded-xl bg-[#89D7B7] text-[#1A312C]"><BriefcaseBusiness className="size-4" /></span><span><span className="block font-mono text-[0.58rem] uppercase tracking-[0.11em] text-[#89D7B7]">Digital Junction</span><span className="mt-0.5 block text-xs font-semibold">Ideas, made practical</span></span></div>
    </div>
  );
}

export default function Home() {
  const products = trpc.portal.products.listPublished.useQuery();
  const projects = trpc.portal.caseStudies.listPublished.useQuery();
  const hero = usePublicSection("home", "hero", getPublicSectionDefault("home", "hero"));
  const serviceOverview = usePublicSection("home", "services", getPublicSectionDefault("home", "services"));
  const productSection = usePublicSection("home", "products", getPublicSectionDefault("home", "products"));
  const projectSection = usePublicSection("home", "projects", getPublicSectionDefault("home", "projects"));
  const story = usePublicSection("home", "story", getPublicSectionDefault("home", "story"));
  const finalCta = usePublicSection("home", "call-to-action", getPublicSectionDefault("home", "call-to-action"));
  const usingSampleProducts = false;
  const featuredProducts = products.data?.filter(product => product.isFeatured).slice(0, 3) ?? products.data?.slice(0, 3) ?? [];
  const usingSampleProjects = false;
  const featuredProjects = projects.data?.slice(0, 3) ?? [];

  return <PublicLayout><main>
    {hero.isVisible && <section className="hero-grid relative isolate overflow-hidden bg-[#1A312C] text-[#FFF4E1]"><div className="hero-orb absolute -right-32 top-0 size-[42rem] opacity-80" /><div className="site-container relative grid min-h-[650px] items-center gap-14 py-20 lg:grid-cols-[1.03fr_.97fr] lg:py-24"><div className="max-w-xl"><p className="font-mono text-[0.69rem] uppercase tracking-[0.15em] text-[#89D7B7]">{hero.eyebrow}</p><h1 className="display mt-6 text-[3.2rem] leading-[0.96] sm:text-6xl lg:text-[4.5rem]">{hero.title}</h1><p className="mt-7 max-w-lg whitespace-pre-line text-base leading-7 text-[#FFF4E1]/72 sm:text-lg">{hero.body}</p><div className="mt-9 flex flex-wrap gap-3"><Link href={hero.ctaHref || "/contact"} className="button-primary buttonlike !bg-[#89D7B7] !text-[#1A312C] hover:!bg-[#FFF4E1]">{hero.ctaLabel || "Start a project"} <ArrowRight className="size-4" /></Link><Link href="/shop" className="button-secondary buttonlike">Explore digital products</Link></div><div className="mt-12 flex flex-wrap items-center gap-3 border-t border-[#FFF4E1]/15 pt-6 font-mono text-[0.65rem] uppercase tracking-[0.09em] text-[#FFF4E1]/55"><span>Technology-driven</span><span className="size-1 rounded-full bg-[#89D7B7]" /><span>Creative</span><span className="size-1 rounded-full bg-[#89D7B7]" /><span>Solution-oriented</span></div></div><div className="relative mx-auto w-full max-w-lg lg:mx-0"><HeroVisual imageUrl={hero.imageUrl} /></div></div></section>}
    {serviceOverview.isVisible && <section className="section-grid py-20 sm:py-28"><div className="site-container"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">{serviceOverview.eyebrow}</p><h2 className="display mt-4 max-w-md text-4xl leading-tight text-[#1A312C]">{serviceOverview.title}</h2><p className="mt-5 max-w-sm whitespace-pre-line text-sm leading-6 text-[#1A312C]/65">{serviceOverview.body}</p><Link href={serviceOverview.ctaHref || "/services"} className="button-quiet buttonlike mt-7">{serviceOverview.ctaLabel || "Explore our services"} <ArrowRight className="size-4" /></Link></div><div className="grid gap-4 sm:grid-cols-2">{solutionGroups.map(({ title, description, Icon }) => <article key={title} className="service-card p-5"><span className="grid size-10 place-items-center rounded-xl bg-[#89D7B7]/35 text-[#1A312C]"><Icon className="size-5" /></span><h3 className="mt-7 text-base font-bold text-[#1A312C]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#1A312C]/63">{description}</p></article>)}</div></div></div></section>}
    <section className="bg-[#FFF4E1] py-20 sm:py-28"><div className="site-container"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow">Our digital services</p><h2 className="display mt-4 max-w-2xl text-4xl leading-tight text-[#1A312C] sm:text-5xl">Technology and creative support for the work ahead.</h2><p className="mt-4 max-w-2xl text-sm leading-6 text-[#1A312C]/65">Professional technology and creative services designed to help businesses establish, improve, and grow their digital presence.</p></div><Link href="/services" className="button-quiet buttonlike w-fit">View all services <ArrowRight className="size-4" /></Link></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{services.map(({ title, description, Icon }) => <article key={title} className="service-card p-5"><span className="grid size-10 place-items-center rounded-xl bg-[#1A312C] text-[#89D7B7]"><Icon className="size-5" /></span><h3 className="mt-6 text-base font-bold text-[#1A312C]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#1A312C]/63">{description}</p><Link href="/services" className="mt-5 inline-flex items-center gap-1.5 text-sm font-bold text-[#428475] hover:text-[#1A312C]">Learn more <ArrowRight className="size-3.5" /></Link></article>)}</div></div></section>
    {productSection.isVisible && <section className="bg-[#1A312C] py-20 text-[#FFF4E1] sm:py-28"><div className="site-container"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="font-mono text-[0.67rem] uppercase tracking-[0.13em] text-[#89D7B7]">{productSection.eyebrow}</p><h2 className="display mt-4 max-w-2xl text-4xl leading-tight sm:text-5xl">{productSection.title}</h2><p className="mt-4 max-w-2xl whitespace-pre-line text-sm leading-6 text-[#FFF4E1]/68">{productSection.body}</p></div><Link href={productSection.ctaHref || "/shop"} className="button-primary buttonlike !bg-[#89D7B7] !text-[#1A312C] hover:!bg-[#FFF4E1]">{productSection.ctaLabel || "Browse all products"} <ArrowRight className="size-4" /></Link></div>{usingSampleProducts && <div className="mt-7 rounded-xl border border-[#89D7B7]/30 bg-[#FFF4E1]/8 px-4 py-3 text-xs leading-5 text-[#FFF4E1]/75"><strong className="text-[#FFF4E1]">Sample preview:</strong> product concepts below are provided only to demonstrate this section; they are not active listings.</div>}{products.isLoading ? <div className="grid min-h-52 place-items-center"><Loader2 className="size-6 animate-spin text-[#89D7B7]" /></div> : featuredProducts.length ? <div className="mt-10 grid gap-5 md:grid-cols-3">{featuredProducts.map(product => <article key={product.id} className="overflow-hidden rounded-[1.2rem] border border-[#FFF4E1]/15 bg-[#FFF4E1]/7">{product.coverImageUrl ? <img src={product.coverImageUrl} alt={product.title} className="aspect-[1.4] w-full object-cover" /> : <div className="aspect-[1.4] bg-[linear-gradient(135deg,#428475,#1A312C)]" />}<div className="p-5"><p className="font-mono text-[0.6rem] uppercase tracking-[0.1em] text-[#89D7B7]">{product.category}</p><div className="mt-2 flex items-start justify-between gap-2"><h3 className="text-base font-bold">{product.title}</h3><span className="font-mono text-xs text-[#89D7B7]">{money(product.price)}</span></div><p className="mt-3 line-clamp-2 text-sm leading-6 text-[#FFF4E1]/65">{product.summary}</p><Link href={`/shop/${product.slug}`} className="mt-5 inline-flex items-center gap-1.5 text-sm font-bold text-[#89D7B7]">View product <ArrowRight className="size-3.5" /></Link></div></article>)}</div> : <div className="mt-10 rounded-[1.2rem] border border-dashed border-[#FFF4E1]/20 p-8 text-center"><p className="text-sm text-[#FFF4E1]/68">Featured products will appear here when they are published by Digital Junction.</p></div>}</div></section>}
    {projectSection.isVisible && <section className="section-grid py-20 sm:py-28"><div className="site-container"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow">Featured projects</p><h2 className="display mt-4 max-w-2xl text-4xl leading-tight text-[#1A312C] sm:text-5xl">{projectSection.title}</h2><p className="mt-4 max-w-2xl whitespace-pre-line text-sm leading-6 text-[#1A312C]/65">{projectSection.body}</p></div><Link href={projectSection.ctaHref || "/work"} className="button-quiet buttonlike w-fit">{projectSection.ctaLabel || "View projects"} <ArrowRight className="size-4" /></Link></div>{usingSampleProjects && <div className="mt-7 rounded-xl border border-[#428475]/20 bg-[#89D7B7]/18 px-4 py-3 text-xs leading-5 text-[#1A312C]/72"><strong className="text-[#1A312C]">Sample concept preview:</strong> these design concepts are not published client work or claimed outcomes.</div>}{projects.isLoading ? <div className="grid min-h-52 place-items-center"><Loader2 className="size-6 animate-spin text-[#428475]" /></div> : featuredProjects.length ? <div className="mt-10 grid gap-5 md:grid-cols-3">{featuredProjects.map(project => <article key={project.id} className="overflow-hidden rounded-[1.2rem] border border-[#1A312C]/12 bg-white/65">{project.coverImageUrl ? <img src={project.coverImageUrl} alt={project.title} className="aspect-[1.4] w-full object-cover" /> : <div className="aspect-[1.4] bg-[linear-gradient(135deg,#1A312C,#428475)]" />}<div className="p-5"><p className="font-mono text-[0.6rem] uppercase tracking-[0.1em] text-[#428475]">{project.category}</p><h3 className="display mt-3 text-2xl text-[#1A312C]">{project.title}</h3><p className="mt-3 line-clamp-3 text-sm leading-6 text-[#1A312C]/64">{project.summary}</p>{project.technologies && <p className="mt-4 font-mono text-[0.58rem] uppercase tracking-[0.09em] text-[#428475]">{project.technologies}</p>}</div></article>)}</div> : <div className="mt-10 rounded-[1.2rem] border border-dashed border-[#1A312C]/18 bg-white/45 p-8 text-center"><p className="eyebrow">Selected work</p><h3 className="display mt-3 text-3xl text-[#1A312C]">Project stories will appear here when they are ready to share.</h3><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-[#1A312C]/62">We only publish work with clear permission and useful context—never invented client stories or results.</p></div>}</div></section>}
    <section className="bg-[#FFF4E1] py-20 sm:py-28"><div className="site-container"><div className="max-w-2xl"><p className="eyebrow">Technology with purpose</p><h2 className="display mt-4 text-4xl leading-tight text-[#1A312C] sm:text-5xl">Thoughtful digital work, built for real progress.</h2></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{advantages.map(([title, description], index) => <article key={title} className="service-card p-6"><span className="font-mono text-[0.66rem] text-[#428475]">0{index + 1}</span><h3 className="mt-7 text-base font-bold text-[#1A312C]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#1A312C]/63">{description}</p></article>)}</div></div></section>
    <section className="bg-[#1A312C] py-20 text-[#FFF4E1] sm:py-28"><div className="site-container"><p className="font-mono text-[0.67rem] uppercase tracking-[0.13em] text-[#89D7B7]">How we work</p><h2 className="display mt-4 max-w-2xl text-4xl leading-tight sm:text-5xl">From idea to digital solution.</h2><div className="mt-12 grid gap-4 md:grid-cols-4">{process.map(([number, title, description], index) => <article key={title} className="relative rounded-[1.2rem] border border-[#FFF4E1]/15 bg-[#FFF4E1]/7 p-6"><span className="font-mono text-[0.7rem] text-[#89D7B7]">{number}</span>{index < process.length - 1 && <span className="absolute -right-2 top-10 hidden size-4 rounded-full border border-[#89D7B7]/45 bg-[#1A312C] md:block" />}<h3 className="display mt-8 text-2xl">{title}</h3><p className="mt-3 text-sm leading-6 text-[#FFF4E1]/65">{description}</p></article>)}</div></div></section>
    {story.isVisible && <section className="section-grid py-20 sm:py-28"><div className="site-container grid gap-10 lg:grid-cols-[.95fr_1.05fr] lg:items-center"><div className="rounded-[1.55rem] bg-[#89D7B7] p-8 text-[#1A312C] sm:p-10">{story.imageUrl ? <img src={story.imageUrl} alt="Digital Junction story" className="mb-7 aspect-[1.7] w-full rounded-xl object-cover" /> : null}<p className="font-mono text-[0.65rem] uppercase tracking-[0.12em] text-[#1A312C]/58">Our story</p><h2 className="display mt-4 text-4xl leading-tight">{story.title}</h2><p className="mt-5 whitespace-pre-line text-sm leading-6 text-[#1A312C]/70">{story.body}</p><Link href={story.ctaHref || "/about"} className="button-quiet buttonlike mt-7 !border-[#1A312C]/20">{story.ctaLabel || "Discover our story"} <ArrowRight className="size-4" /></Link></div><div><p className="eyebrow">A practical partnership</p><h2 className="display mt-4 text-4xl leading-tight text-[#1A312C]">Software development, creative design, and digital products in one considered direction.</h2><p className="mt-5 max-w-xl text-sm leading-7 text-[#1A312C]/64">The company combines software development, creative design, and digital products to help businesses and individuals build better digital experiences—without unnecessary complexity.</p></div></div></section>}
    {finalCta.isVisible && <section className="bg-[#FFF4E1] py-20"><div className="site-container rounded-[1.6rem] bg-[#428475] p-8 text-[#FFF4E1] sm:p-12"><div className="grid gap-8 md:grid-cols-[1fr_auto] md:items-center"><div>{finalCta.imageUrl ? <img src={finalCta.imageUrl} alt="" className="mb-6 max-h-40 w-full rounded-xl object-cover md:max-w-md" /> : null}<p className="font-mono text-[0.66rem] uppercase tracking-[0.13em] text-[#89D7B7]">Start the next chapter</p><h2 className="display mt-3 max-w-2xl text-4xl">{finalCta.title}</h2><p className="mt-4 max-w-2xl whitespace-pre-line text-sm leading-6 text-[#FFF4E1]/75">{finalCta.body}</p></div><div className="flex flex-wrap gap-3"><Link href={finalCta.ctaHref || "/contact"} className="button-primary buttonlike !bg-[#89D7B7] !text-[#1A312C] hover:!bg-[#FFF4E1]">{finalCta.ctaLabel || "Start a project"} <ArrowRight className="size-4" /></Link><Link href="/shop" className="button-secondary buttonlike">Explore products</Link></div></div></div></section>}
  </main></PublicLayout>;
}
