import { ArrowLeft, Check, CheckCircle2, Loader2, Send } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { Link, useRoute } from "wouter";
import PublicLayout from "@/components/PublicLayout";
import { trpc } from "@/lib/trpc";

function money(value: string | number) { return new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP", maximumFractionDigits: 2 }).format(Number(value)); }

export default function ProductDetail() {
  const [, params] = useRoute("/shop/:handle");
  const input = useMemo(() => ({ slug: params?.handle ?? "" }), [params?.handle]);
  const { data: product, isLoading, error } = trpc.portal.products.bySlug.useQuery(input, { enabled: Boolean(input.slug) });
  const [submitted, setSubmitted] = useState(false);
  const inquiry = trpc.portal.products.inquire.useMutation({ onSuccess: () => setSubmitted(true) });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!product) return; const form = new FormData(event.currentTarget); inquiry.mutate({ productId: product.id, name: String(form.get("name")), email: String(form.get("email")), message: String(form.get("message")) }); };
  if (isLoading) return <PublicLayout><main className="grid min-h-[60vh] place-items-center"><Loader2 className="size-7 animate-spin text-[#428475]" /></main></PublicLayout>;
  if (!product || error) return <PublicLayout><main className="site-container py-24"><Link href="/shop" className="inline-flex items-center gap-2 text-sm font-bold text-[#428475]"><ArrowLeft className="size-4" />Back to products</Link><h1 className="display mt-8 text-5xl text-[#1A312C]">That product is not available.</h1></main></PublicLayout>;
  return <PublicLayout><main><section className="section-grid py-10 sm:py-16"><div className="site-container"><Link href="/shop" className="inline-flex items-center gap-2 text-sm font-bold text-[#428475] hover:text-[#1A312C]"><ArrowLeft className="size-4" />Back to products</Link><div className="mt-8 grid gap-10 lg:grid-cols-[1.08fr_.92fr]"><div className="overflow-hidden rounded-[1.5rem] bg-[#89D7B7]/25">{product.coverImageUrl ? <img src={product.coverImageUrl} alt={product.title} className="aspect-[1.18] size-full object-cover" /> : <div className="aspect-[1.18] bg-[linear-gradient(135deg,#1A312C,#428475)]" />}</div><div className="lg:pt-6"><p className="font-mono text-[0.66rem] uppercase tracking-[0.12em] text-[#428475]">{product.category}</p><h1 className="display mt-4 text-5xl leading-[0.98] text-[#1A312C]">{product.title}</h1><p className="mt-6 text-base leading-7 text-[#1A312C]/68">{product.description || product.summary}</p><div className="mt-8 flex items-center justify-between border-y border-[#1A312C]/12 py-5"><span className="text-sm text-[#1A312C]/65">Digital product</span><strong className="font-display text-3xl text-[#1A312C]">{money(product.price)}</strong></div>{submitted ? <div className="mt-6 rounded-2xl bg-[#89D7B7]/35 p-6"><CheckCircle2 className="size-6 text-[#1A312C]" /><h2 className="display mt-4 text-2xl text-[#1A312C]">Enquiry received.</h2><p className="mt-2 text-sm leading-6 text-[#1A312C]/68">Digital Junction will respond directly about this product. No third-party checkout is involved.</p></div> : <form onSubmit={submit} className="mt-6 grid gap-3 rounded-2xl border border-[#1A312C]/12 bg-white/65 p-5"><p className="font-mono text-[0.62rem] uppercase tracking-[0.1em] text-[#428475]">Request this product</p><div className="grid gap-3 sm:grid-cols-2"><input required name="name" className="form-field !py-2 text-sm" placeholder="Your name" /><input required type="email" name="email" className="form-field !py-2 text-sm" placeholder="Email address" /></div><textarea required minLength={10} name="message" className="form-field min-h-24 resize-y text-sm" placeholder="Tell us how you plan to use this product." />{inquiry.error && <p className="text-sm text-red-700">We could not send that enquiry. Please try again.</p>}<button className="button-primary w-fit disabled:opacity-60" disabled={inquiry.isPending}>{inquiry.isPending ? <Loader2 className="size-4 animate-spin" /> : <Send className="size-4" />}Send enquiry</button></form>}<div className="mt-8 grid gap-3">{["Directly managed by Digital Junction", "No third-party storefront or checkout", "We will reply with the next steps and delivery details"].map(item => <div key={item} className="flex items-center gap-3 text-sm text-[#1A312C]/67"><span className="grid size-5 place-items-center rounded-full bg-[#89D7B7]/35 text-[#1A312C]"><Check className="size-3" /></span>{item}</div>)}</div></div></div></div></section></main></PublicLayout>;
}
