import type { LucideIcon } from "lucide-react";
import { ArrowRight, Code2, FileText, Globe2, LayoutDashboard, MonitorCog, Palette, Smartphone, Video, Workflow, Wrench } from "lucide-react";
import { Link } from "wouter";
import PublicLayout from "@/components/PublicLayout";

const services: { number: string; title: string; description: string; details: string[]; icon: LucideIcon }[] = [
  { number: "01", title: "Web Development", description: "Professional, responsive, and SEO-friendly websites that make it easier for customers to understand and act.", details: ["Company websites", "Landing pages", "Custom web systems"], icon: Globe2 },
  { number: "02", title: "UI/UX Design", description: "Modern, intuitive, user-centred interfaces that turn complex requirements into useful experiences.", details: ["Wireframes", "High-fidelity UI", "Interactive prototypes"], icon: Palette },
  { number: "03", title: "Full-Stack Development", description: "Complete frontend, backend, database, and API solutions for more capable digital products.", details: ["Web applications", "Databases", "API integration"], icon: Code2 },
  { number: "04", title: "Mobile App Development", description: "Cross-platform mobile applications designed around the moments when work happens away from a desk.", details: ["Business apps", "Customer experiences", "Mobile UI"], icon: Smartphone },
  { number: "05", title: "POS & Inventory Systems", description: "Business management solutions for sales, inventory, reporting, and operations.", details: ["POS workflows", "Inventory tools", "Management dashboards"], icon: LayoutDashboard },
  { number: "06", title: "Logo & Branding", description: "Professional visual identities and practical brand assets designed for businesses and growing teams.", details: ["Logo systems", "Visual identity", "Brand assets"], icon: MonitorCog },
  { number: "07", title: "Canva Template Design", description: "Editable templates for businesses, creators, and professionals who need a consistent visual starting point.", details: ["Social templates", "Presentation assets", "Marketing kits"], icon: FileText },
  { number: "08", title: "Short-form Video Editing", description: "Engaging content optimised for TikTok, Facebook Reels, Instagram Reels, and YouTube Shorts.", details: ["Social edits", "Reels & Shorts", "Content packaging"], icon: Video },
  { number: "09", title: "Technical Support", description: "Practical assistance for software, hardware, systems, and basic networking needs.", details: ["Software support", "System setup", "Basic IT guidance"], icon: Wrench },
];

export default function Services() { return <PublicLayout><main><section className="bg-[#1A312C] py-20 text-[#FFF4E1] sm:py-28"><div className="site-container max-w-5xl"><p className="font-mono text-[0.68rem] uppercase tracking-[0.14em] text-[#89D7B7]">Services</p><h1 className="display mt-5 max-w-4xl text-5xl leading-[0.98] sm:text-6xl">Digital services designed to move your work <em className="font-normal text-[#89D7B7]">forward.</em></h1><p className="mt-7 max-w-2xl text-base leading-7 text-[#FFF4E1]/72">Digital Junction combines technology, creative design, business systems, and practical support to help companies and creators build better digital experiences.</p></div></section><section className="section-grid py-16 sm:py-24"><div className="site-container"><div className="grid gap-4">{services.map(service => { const Icon = service.icon; return <article key={service.number} className="service-card grid gap-6 p-6 md:grid-cols-[4rem_1fr_auto] md:items-center md:p-8"><div className="flex items-center gap-4 md:block"><span className="font-mono text-xs text-[#428475]">{service.number}</span><span className="grid size-11 place-items-center rounded-xl bg-[#89D7B7]/35 text-[#1A312C] md:mt-5"><Icon className="size-5" /></span></div><div><h2 className="display text-3xl text-[#1A312C]">{service.title}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#1A312C]/63">{service.description}</p><div className="mt-4 flex flex-wrap gap-2">{service.details.map(detail => <span key={detail} className="rounded-full border border-[#1A312C]/12 bg-white/45 px-3 py-1.5 text-xs font-medium text-[#1A312C]/75">{detail}</span>)}</div></div><Link href="/contact" className="button-quiet buttonlike w-fit">Discuss this service <ArrowRight className="size-4" /></Link></article>})}</div></div></section><section className="bg-[#89D7B7] py-16"><div className="site-container grid gap-8 md:grid-cols-[1fr_auto] md:items-center"><div><p className="eyebrow !text-[#1A312C]/65">Not sure where to start?</p><h2 className="display mt-3 max-w-2xl text-4xl text-[#1A312C]">The best first step is often getting clear on the right question.</h2></div><Link href="/contact" className="button-primary buttonlike">Start a conversation <ArrowRight className="size-4" /></Link></div></section></main></PublicLayout>; }
