import type { LucideIcon } from "lucide-react";
import { ArrowRight, Code2, FileText, Globe2, LayoutDashboard, MonitorCog, Palette, Smartphone, Video, Wrench } from "lucide-react";
import { Link } from "wouter";
import PublicLayout from "@/components/PublicLayout";
import { usePublicSection } from "@/hooks/usePublicSection";

const services: { number: string; title: string; description: string; details: string[]; icon: LucideIcon }[] = [
  { number: "01", title: "Web Development", description: "Professional, responsive, and SEO-friendly websites that make it easier for customers to understand and act.", details: ["Company websites", "Landing pages", "Custom web systems"], icon: Globe2 },
  { number: "02", title: "UI/UX Design", description: "Modern, intuitive, user-centred interfaces that turn complex requirements into useful experiences.", details: ["Wireframes", "High-fidelity UI", "Interactive prototypes"], icon: Palette },
  { number: "03", title: "Full-Stack Development", description: "Complete frontend, backend, database, and API solutions for more capable digital products.", details: ["Web applications", "Databases", "API integration"], icon: Code2 },
  { number: "04", title: "Mobile App Development", description: "Cross-platform mobile applications designed around the moments when work happens away from a desk.", details: ["Business apps", "Customer experiences", "Mobile UI"], icon: Smartphone },
  { number: "05", title: "POS & Inventory Systems", description: "Business management solutions for sales, inventory, reporting, and operations.", details: ["POS workflows", "Inventory tools", "Management dashboards"], icon: LayoutDashboard },
  { number: "06", title: "Logo & Branding", description: "Professional visual identities and practical brand assets designed for businesses and growing teams.", details: ["Logo systems", "Visual identity", "Brand assets"], icon: MonitorCog },
  { number: "07", title: "Canva Template Design", description: "Editable templates for businesses, creators, and professionals who need a consistent visual starting point.", details: ["Social templates", "Presentation assets", "Marketing kits"], icon: FileText },
  { number: "08", title: "Short-form Video Editing", description: "Engaging content optimised for TikTok, Facebook Reels, Instagram Reels, and YouTube Shorts.", details: ["Social edits", "Reels & Shorts", "Content packaging"], icon: Video },
  { number: "09", title: "Technical Support", description: "Practical assistance for software, hardware, systems, and basic networking needs.", details: ["Software support", "System setup", "Basic IT guidance"], icon: Wrench },
];

export default function Services() {
  const hero = usePublicSection("services", "hero", { title: "Digital services designed to move your work forward.", body: "Digital Junction combines technology, creative design, business systems, and practical support to help companies and creators build better digital experiences." });
  const serviceList = usePublicSection("services", "service-list", { title: "Services built around practical outcomes.", body: "Explore the capabilities available from Digital Junction.", ctaLabel: "Discuss this service", ctaHref: "/contact" });
  const cta = usePublicSection("services", "call-to-action", { title: "The best first step is often getting clear on the right question.", body: "", ctaLabel: "Start a conversation", ctaHref: "/contact" });
  return <PublicLayout><main>
    {hero.isVisible && <section className="bg-[#1A312C] py-20 text-[#FFF4E1] sm:py-28"><div className="site-container max-w-5xl">{hero.imageUrl ? <img src={hero.imageUrl} alt="Services" className="mb-8 max-h-80 w-full rounded-[1.4rem] object-cover" /> : null}<p className="font-mono text-[0.68rem] uppercase tracking-[0.14em] text-[#89D7B7]">Services</p><h1 className="display mt-5 max-w-4xl whitespace-pre-line text-5xl leading-[0.98] sm:text-6xl">{hero.title}</h1><p className="mt-7 max-w-2xl whitespace-pre-line text-base leading-7 text-[#FFF4E1]/72">{hero.body}</p></div></section>}
    {serviceList.isVisible && <section className="section-grid py-16 sm:py-24"><div className="site-container"><div className="mb-10 max-w-2xl"><p className="eyebrow">Service list</p><h2 className="display mt-3 text-4xl text-[#1A312C]">{serviceList.title}</h2>{serviceList.body ? <p className="mt-3 whitespace-pre-line text-sm leading-6 text-[#1A312C]/65">{serviceList.body}</p> : null}</div><div className="grid gap-4">{services.map(service => { const Icon = service.icon; return <article key={service.number} className="service-card grid gap-6 p-6 md:grid-cols-[4rem_1fr_auto] md:items-center md:p-8"><div className="flex items-center gap-4 md:block"><span className="font-mono text-xs text-[#428475]">{service.number}</span><span className="grid size-11 place-items-center rounded-xl bg-[#89D7B7]/35 text-[#1A312C] md:mt-5"><Icon className="size-5" /></span></div><div><h2 className="display text-3xl text-[#1A312C]">{service.title}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#1A312C]/63">{service.description}</p><div className="mt-4 flex flex-wrap gap-2">{service.details.map(detail => <span key={detail} className="rounded-full border border-[#1A312C]/12 bg-white/45 px-3 py-1.5 text-xs font-medium text-[#1A312C]/75">{detail}</span>)}</div></div><Link href={serviceList.ctaHref || "/contact"} className="button-quiet buttonlike w-fit">{serviceList.ctaLabel || "Discuss this service"} <ArrowRight className="size-4" /></Link></article>; })}</div></div></section>}
    {cta.isVisible && <section className="bg-[#89D7B7] py-16"><div className="site-container grid gap-8 md:grid-cols-[1fr_auto] md:items-center"><div>{cta.imageUrl ? <img src={cta.imageUrl} alt="" className="mb-6 max-h-40 rounded-xl object-cover" /> : null}<p className="eyebrow !text-[#1A312C]/65">Not sure where to start?</p><h2 className="display mt-3 max-w-2xl whitespace-pre-line text-4xl text-[#1A312C]">{cta.title}</h2>{cta.body ? <p className="mt-3 max-w-2xl whitespace-pre-line text-sm leading-6 text-[#1A312C]/70">{cta.body}</p> : null}</div><Link href={cta.ctaHref || "/contact"} className="button-primary buttonlike">{cta.ctaLabel || "Start a conversation"} <ArrowRight className="size-4" /></Link></div></section>}
  </main></PublicLayout>;
}
