import { ArrowRight, Code2, MonitorCog, Palette, Smartphone, Workflow } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { Link } from "wouter";
import PublicLayout from "@/components/PublicLayout";

const services: { number: string; title: string; description: string; details: string[]; icon: LucideIcon }[] = [
  { number: "01", title: "Web development", description: "Responsive, focused websites that make it easier for people to understand and act.", details: ["Company and portfolio sites", "Landing pages and e-commerce", "Custom web systems"], icon: Code2 },
  { number: "02", title: "UI/UX design", description: "Clear interface systems that turn complex requirements into calm, useful experiences.", details: ["Wireframes and high-fidelity UI", "Dashboards and web apps", "Interactive prototypes"], icon: Palette },
  { number: "03", title: "Business systems", description: "Practical operational software for teams that have outgrown disconnected processes.", details: ["Client portals and workflows", "POS and inventory concepts", "Role-based business tools"], icon: Workflow },
  { number: "04", title: "Mobile applications", description: "Mobile-first products designed around the moments when a desk is not nearby.", details: ["Business and ordering apps", "Booking experiences", "Companion application UI"], icon: Smartphone },
  { number: "05", title: "Digital products", description: "Reusable digital resources that give teams and creators a more considered starting point.", details: ["Website and UI templates", "Component and design kits", "Business-ready digital assets"], icon: MonitorCog },
];

export default function Services() {
  return <PublicLayout><main><section className="bg-[#1A312C] py-20 text-[#FFF4E1] sm:py-28"><div className="site-container max-w-5xl"><p className="font-mono text-[0.68rem] uppercase tracking-[0.14em] text-[#89D7B7]">Services</p><h1 className="display mt-5 max-w-4xl text-5xl leading-[0.98] sm:text-6xl">Digital work that turns direction into <em className="font-normal text-[#89D7B7]">momentum.</em></h1><p className="mt-7 max-w-2xl text-base leading-7 text-[#FFF4E1]/72">Each engagement begins with the reality of the work: the people involved, the constraints, the decisions to make, and the outcome worth moving toward.</p></div></section><section className="section-grid py-16 sm:py-24"><div className="site-container"><div className="grid gap-4">{services.map(service => { const Icon = service.icon; return <article key={service.number} className="service-card grid gap-6 p-6 md:grid-cols-[4rem_1fr_auto] md:items-center md:p-8"><div className="flex items-center gap-4 md:block"><span className="font-mono text-xs text-[#428475]">{service.number}</span><span className="grid size-11 place-items-center rounded-xl bg-[#89D7B7]/35 text-[#1A312C] md:mt-5"><Icon className="size-5" /></span></div><div><h2 className="display text-3xl text-[#1A312C]">{service.title}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#1A312C]/63">{service.description}</p><div className="mt-4 flex flex-wrap gap-2">{service.details.map(detail => <span key={detail} className="rounded-full border border-[#1A312C]/12 bg-white/45 px-3 py-1.5 text-xs font-medium text-[#1A312C]/75">{detail}</span>)}</div></div><Link href="/contact" className="button-quiet buttonlike w-fit">Discuss this service <ArrowRight className="size-4" /></Link></article>})}</div></div></section><section className="bg-[#89D7B7] py-16"><div className="site-container grid gap-8 md:grid-cols-[1fr_auto] md:items-center"><div><p className="eyebrow !text-[#1A312C]/65">Not sure where to start?</p><h2 className="display mt-3 max-w-2xl text-4xl text-[#1A312C]">The best first step is often getting clear on the right question.</h2></div><Link href="/contact" className="button-primary buttonlike">Start a conversation <ArrowRight className="size-4" /></Link></div></section></main></PublicLayout>;
}
