import { ArrowRight, ArrowUpRight, Loader2 } from "lucide-react";
import { Link } from "wouter";
import PublicLayout from "@/components/PublicLayout";
import { usePublicSection } from "@/hooks/usePublicSection";
import { trpc } from "@/lib/trpc";
import { sampleProjects } from "@/data/samplePreview";

export default function Work() {
  const { data: caseStudies = [], isLoading } = trpc.portal.caseStudies.listPublished.useQuery();
  const hero = usePublicSection("work", "hero", { title: "Work with a clear reason to exist.", body: "A focused collection of publicly shareable projects, with the context, decisions, and outcomes that made each one meaningful." });
  const projectSection = usePublicSection("work", "projects", { title: "Selected projects", body: "Publicly shareable Digital Junction work." });
  const cta = usePublicSection("work", "call-to-action", { title: "Bring the brief, the friction point, or the half-formed idea.", ctaLabel: "Start a project", ctaHref: "/contact" });
  const usingSamples = caseStudies.length === 0;
  const studies = usingSamples ? sampleProjects : caseStudies;
  return <PublicLayout><main>
    {hero.isVisible && <section className="bg-[#FFF4E1] py-20 sm:py-28"><div className="site-container grid gap-10 lg:grid-cols-[1.1fr_.9fr] lg:items-end"><div>{hero.imageUrl ? <img src={hero.imageUrl} alt="Selected work" className="mb-7 max-h-72 w-full rounded-[1.4rem] object-cover" /> : null}<p className="eyebrow">Selected work</p><h1 className="display mt-4 whitespace-pre-line text-5xl leading-[0.98] text-[#1A312C] sm:text-6xl">{hero.title}</h1></div><p className="max-w-md whitespace-pre-line text-base leading-7 text-[#1A312C]/65">{hero.body}</p></div>{usingSamples && <div className="site-container mt-8"><div className="rounded-xl border border-[#428475]/20 bg-[#89D7B7]/18 px-4 py-3 text-xs leading-5 text-[#1A312C]/72"><strong className="font-bold text-[#1A312C]">Concept preview mode:</strong> the ten projects below are sample concepts added only to demonstrate the layout. They do not represent clients, delivered work, or claimed results.</div></div>}</section>}
    {projectSection.isVisible && <section className="section-grid border-y border-[#1A312C]/10 py-16 sm:py-24"><div className="site-container">{projectSection.title || projectSection.body ? <div className="mb-8 max-w-2xl"><p className="eyebrow">Projects</p>{projectSection.title ? <h2 className="display mt-3 text-4xl text-[#1A312C]">{projectSection.title}</h2> : null}{projectSection.body ? <p className="mt-3 whitespace-pre-line text-sm leading-6 text-[#1A312C]/65">{projectSection.body}</p> : null}</div> : null}{isLoading ? <div className="grid min-h-72 place-items-center"><Loader2 className="size-7 animate-spin text-[#428475]" /></div> : <div className="grid gap-5 md:grid-cols-2">{studies.map((study, index) => <article key={study.id} className={`overflow-hidden rounded-[1.4rem] ${index % 2 === 0 ? "bg-[#1A312C] text-[#FFF4E1]" : "border border-[#1A312C]/10 bg-white/65 text-[#1A312C]"}`}>{study.coverImageUrl ? <img src={study.coverImageUrl} alt={study.title} className="aspect-[1.8] w-full object-cover" /> : <div className={`relative aspect-[1.8] overflow-hidden ${index % 2 === 0 ? "bg-[linear-gradient(135deg,#1A312C,#428475)]" : "bg-[linear-gradient(135deg,#89D7B7,#dff4e8)]"}`}><span className={`absolute left-6 top-6 font-mono text-[0.58rem] uppercase tracking-[0.11em] ${index % 2 === 0 ? "text-[#89D7B7]" : "text-[#1A312C]/60"}`}>Digital Junction</span></div>}<div className="p-7"><div className="flex items-start justify-between gap-4"><div><p className={`font-mono text-[0.63rem] uppercase tracking-[0.11em] ${index % 2 === 0 ? "text-[#89D7B7]" : "text-[#428475]"}`}>{study.category}</p>{"isSample" in study && <span className={`mt-2 inline-block rounded-full px-2 py-1 font-mono text-[0.5rem] uppercase tracking-[0.08em] ${index % 2 === 0 ? "bg-[#89D7B7]/18 text-[#89D7B7]" : "bg-[#89D7B7]/30 text-[#1A312C]/65"}`}>Sample concept</span>}</div><ArrowUpRight className="size-4" /></div><h2 className="display mt-7 text-3xl">{study.title}</h2><p className={`mt-3 max-w-lg text-sm leading-6 ${index % 2 === 0 ? "text-[#FFF4E1]/68" : "text-[#1A312C]/64"}`}>{study.summary}</p>{study.technologies && <p className={`mt-5 font-mono text-[0.61rem] uppercase tracking-[0.1em] ${index % 2 === 0 ? "text-[#89D7B7]" : "text-[#428475]"}`}>{study.technologies}</p>}</div></article>)}</div>}</div></section>}
    {cta.isVisible && <section className="bg-[#FFF4E1] py-20"><div className="site-container rounded-[1.5rem] bg-[#428475] p-8 text-[#FFF4E1] sm:p-12"><div className="grid gap-8 md:grid-cols-[1fr_auto] md:items-center"><div>{cta.imageUrl ? <img src={cta.imageUrl} alt="" className="mb-6 max-h-40 w-full rounded-xl object-cover md:max-w-md" /> : null}<p className="font-mono text-[0.66rem] uppercase tracking-[0.13em] text-[#89D7B7]">Your work could be next</p><h2 className="display mt-3 max-w-2xl whitespace-pre-line text-4xl">{cta.title}</h2>{cta.body ? <p className="mt-3 whitespace-pre-line text-sm leading-6 text-[#FFF4E1]/75">{cta.body}</p> : null}</div><Link href={cta.ctaHref || "/contact"} className="button-secondary buttonlike w-fit">{cta.ctaLabel || "Start a project"} <ArrowRight className="size-4" /></Link></div></div></section>}
  </main></PublicLayout>;
}
